### ISSUE TITLE
Any plan for a ForgetMeChunk mod compatibility?

### ISSUE THREAD

**Issue by NaiNonTH** [mjwells2002/ForgetMeChunk#7]
According to the Fabric Loader's error dialog box...
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Debugify' (debugify) 1.5.0 with any version that is compatible with:
		 - forgetmechunk 1.18.X-1.0.3
Unmet dependency listing:
	 - Mod 'Debugify' (debugify) 1.5.0 is incompatible with any version of mod 'Forget Me Chunk' (forgetmechunk), but a matching version is present: 1.18.X-1.0.3!
	 - Mod 'Tinfoiled Cotton Client Commands' (cotton-client-commands) 1.1.0+1.15.2 requires any version between 1.14- (inclusive) and 1.16- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.6+266-main requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.6+266-main requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.6+266-main requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.6+266-main requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.18.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by NaiNonTH** [comment]
Wrong one. Sorry

**Comment by NaiNonTH** [comment]
Mistaken... should not be created at the very first place.

**Comment by mjwells2002** [comment]
As you probably already found out debugify contains the exact same fix that I created for this mod and as such is not compatible
